
# These are supported funding model platforms

github: [DarkSylver, CloudStudio-DeviceModels-Scripts, Parsing.Tools, Sylsoft-Software-Design, SylverDotNet, SylDotNet, DarkSylver-Sandbox, DarkSylver-P1, DarkSylver-P2, DarkSylver-P3, Brainstorming-DS, Brainstorming-DS2, Brainstorming-DS3, Brainstorming-DS4]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
